---
default:
  driver: redis
  options:
    key_prefix: ${DEFAULT_REDIS_KEY_PREFIX}
    servers:
      default:
        host: ${DEFAULT_REDIS_HOST}
        port: ${DEFAULT_REDIS_PORT}
chemdb:
  driver: redis
  options:
    key_prefix: ${CHEMDB_REDIS_KEY_PREFIX}
    servers:
      default:
        host: ${CHEMDB_REDIS_HOST}
        port: ${CHEMDB_REDIS_PORT}
unitconv:
  driver: redis
  options:
    key_prefix: ${UNITCONV_REDIS_KEY_PREFIX}
    servers:
      default:
        host: ${UNITCONV_REDIS_HOST}
        port: ${UNITCONV_REDIS_PORT}
...
