<form class="form" method="POST" action="">
    <div class="form-group add-members-email">
        <label class="text-muted"><?=H(T('输入成员Email, 多个Email使用逗号(,)分隔:'))?></label>
        <textarea class="form-control" name="email" rows="5"><?=H($data)?></textarea>
    </div>
    <div class="form-group text-right">
        <input type="button" class="btn btn-default" data-dismiss="modal" value="<?=H(T('取消'))?>" />
        <input type="submit" class="btn btn-primary" value="<?=H(T('提交'))?>" />
    </div>
</form>
