---
title: ${LAB_APP_TITLE}
node: ${MALL_NODE}
auto_install_apps_for_new_group:
  - ${LAB_ORDERS_GAPPER_ID}
  - ${LAB_INVENTORY_GAPPER_ID}
  - ${LAB_GRANTS_GAPPER_ID}
  - ${LAB_WASTE_GAPPER_ID}
  - ${LAB_WASTE_BOTTLE_GAPPER_ID}
...
