<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="text-center modal-body clearfix" data-gid="<?=H($group)?>" data-callback>
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <div class="add-member-icon select-member-handler" data-require="lab-orders-add-member">
                    <div class="add-member-icon-image"><img src="<?=H($data['demo'])?>" /></div>
                    <div class="add-member-icon-title"><?=H(T('一卡通成员'))?></div>
                </div>
            </div>
        </div>
    </div>
</div>
