default:
  dsn: mysql:dbname=${DB_PREFIX}_admin;host=${DB_HOST};port=${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASS}

hazardous: # 用来获取危化品管理员设置的分级审查信息
  dsn: mysql:dbname=${DB_PREFIX}_admin;host=${DB_HOST};port=${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASS}
