---
clients:
  default:
    driver: database
  rpc:
    driver: RPC
    options:
      url: ${TAGDB_API}
      client:
        id: ${ORDER_REVIEW_GAPPER_ID}
        secret: ${ORDER_REVIEW_GAPPER_SECRET}
...
